<a href="https://colab.research.google.com/github/Fulmo/ML_ITMM/blob/master/cv_lab2_3DConv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
def Conv3D(input_shape: np.array, kernel: np.array):
  _X    = 0
  _Y    = 0

  dimX = 1
  dimY = 1
  conv_shape = np.zeros(shape=[len(kernel),len(kernel[0]),len(kernel[0][0])], dtype=np.uint8)

  for i in range(0, len(input_shape)-len(kernel)+1, dimX):
    for j in range(0, len(input_shape[0])-len(kernel[0])+1, dimY):
      output = 0
      for x in range(len(kernel)):
        for y in range(len(kernel[0])):
          for z in range(len(kernel[0][0])):
            output = output + input_shape[x+i, y+j]*kernel[x, y]      
      conv_shape[_X, _Y] = output
      _Y = _Y + 1
    _X = _X + 1
    _Y=0
  return conv_shape

In [0]:
data_shape = np.ones((3,3))
data_shape
data_shape = data_shape.astype(np.int32)

In [0]:
kernel = np.array([ [[1, 1], [1, 1]], 
                      [[1, 1], [1, 1]]
                    ], np.int32)
kernel

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [0]:
print(Conv3D(data_shape, kernel = kernel))

[[[8 8]
  [8 8]]

 [[8 8]
  [8 8]]]


In [0]:
input_shape = np.random.rand(3, 3)
input_shape

array([[0.62642314, 0.38362001, 0.41565618],
       [0.79198026, 0.44746767, 0.4389996 ],
       [0.15222564, 0.65350964, 0.50361766]])

In [0]:
kernel_new = np.array([ [[3, 2], [1, 5]], 
                      [[6, 3], [4, 3]]
                    ], np.int32)

In [0]:
print(Conv3D(input_shape, kernel_new))

[[[17 13]
  [12 11]]

 [[12 12]
  [15 13]]]
